2024-10-21 23:45:15 --> >>System.InvalidOperationException: The connection is already open.
   en MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   en MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   en MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__94.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MySql.Data.MySqlClient.MySqlConnection.Open()
   en ProyectoObrador.Datos.DatosEmpleados.agregarEmpleado(Empleado _empleado) en D:\ProyectoObrador\ProyectoObrador\Datos\DatosEmpleados.cs:línea 69
2024-10-21 23:45:26 --> >>System.InvalidOperationException: The connection is already open.
   en MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   en MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   en MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__94.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MySql.Data.MySqlClient.MySqlConnection.Open()
   en ProyectoObrador.Datos.DatosEmpleados.agregarEmpleado(Empleado _empleado) en D:\ProyectoObrador\ProyectoObrador\Datos\DatosEmpleados.cs:línea 69
